FROM arm64v8/ros:humble
ARG USERNAME=slam
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Add new user as a sudoer.
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && usermod -aG sudo $USERNAME \
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

#RUN apt install -y 

USER $USERNAME
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USERNAME/.bashrc  # Source ROS installation
RUN echo "FILE=/workspaces/RPW_vislam/slam_ws/install/setup.bash && test -f \$FILE && source \$FILE" >> /home/$USERNAME/.bashrc  # Source ROS workspace
RUN echo "cd /workspaces/RPW_vislam/slam_ws" >> /home/$USERNAME/.bashrc
RUN sudo chsh -s /bin/bash ${USERNAME}
WORKDIR /workspaces/RPW_vislam/slam_ws
