services:
  ros2_cam:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: ros2_stereo_cam
    runtime: nvidia
    privileged: true
    network_mode: host
    ipc: host

    tty: true
    stdin_open: true

    command: bash -lc "/workspaces/RPW_vislam/cam_ws/entrypoint.sh"

    environment:
      - DISPLAY=${DISPLAY:-localhost:10.0}
      - XAUTHORITY=${XAUTHORITY:-/home/nvidia/.docker.xauth}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GST_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:/usr/local/lib:${LD_LIBRARY_PATH}

    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/nvidia/.docker.xauth:/home/nvidia/.docker.xauth:ro
      - /dev:/dev:rw
      - /sys:/sys:ro
      - ./:/workspaces/RPW_ros2_ws:rw
      - /dev/i2c-8:/dev/i2c-8:rw   # I2C device for IMU

  ros2_slam:
    build:
      context: .
      dockerfile: Dockerfile.slam
    container_name: ros2_slam
    runtime: nvidia
    privileged: true
    network_mode: host
    ipc: host

    tty: true
    stdin_open: true

    command: sleep infinity   # <-- keeps container running

    environment:
      - DISPLAY=${DISPLAY:-localhost:10.0}
      - XAUTHORITY=${XAUTHORITY:-/home/nvidia/.docker.xauth}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - GST_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:/usr/local/lib:${LD_LIBRARY_PATH}

    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/nvidia/.docker.xauth:/home/nvidia/.docker.xauth:ro
      - /dev:/dev:rw
      - /sys:/sys:ro
      - /tmp/argus_socket:/tmp/argus_socket
      - ./:/workspaces/RPW_ros2_ws:rw
