FROM arm64v8/ros:humble

ARG USERNAME=slam
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive
ENV VISLAM_WS=/opt/vislam_ws

# ---------- User ----------
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi && \
    groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    apt-get update && apt-get install -y sudo && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# ---------- Dependencies ----------
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    build-essential \
    python3-colcon-common-extensions \
    python3-rosdep \
    libopencv-dev \
    libeigen3-dev \
    libboost-all-dev

RUN rosdep init || true
RUN rosdep update

# ---------- Workspace ----------
WORKDIR ${VISLAM_WS}
RUN mkdir -p src

# ---------- Clone repos ----------
WORKDIR ${VISLAM_WS}/src
RUN git clone https://github.com/Silviis/VINS-Fusion-ROS2.git && \
    git clone https://github.com/Silviis/rtabmap.git && \
    git clone https://github.com/Silviis/rtabmap_ros.git

# ---------- Install ROS deps ----------
WORKDIR ${VISLAM_WS}
RUN rosdep install --from-paths src --ignore-src -r -y

# =========================================================
# PHASE 1: Build VINS-Fusion only
# =========================================================
RUN . /opt/ros/humble/setup.sh && \
    colcon build --packages-select camera_models global_fusion loop_fusion vins  --cmake-args -DCMAKE_BUILD_TYPE=Release

# =========================================================
# PHASE 2: Build rtabmap WITH VINS support
# =========================================================
RUN . /opt/ros/humble/setup.sh && \
    . ${VISLAM_WS}/install/setup.sh && \
    MAKEFLAGS="-j4" colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

# ---------- Runtime user ----------
USER $USERNAME
RUN echo "source /opt/ros/humble/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "source ${VISLAM_WS}/install/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "cd ${VISLAM_WS}" >> /home/$USERNAME/.bashrc

CMD ["bash"]
